# Generated by Django 4.0.4 on 2022-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipatinggroup',
            old_name='user_id',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='eventparticipatinggroup',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='cyclingevent',
            name='event_name',
            field=models.TextField(verbose_name='Cycling Event'),
        ),
    ]
