# Generated by Django 4.0.4 on 2022-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('CPL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclingevent',
            name='cycling_event_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
