# Generated by Django 4.0.4 on 2022-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('CPL', '0002_alter_cyclingevent_cycling_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cyclingevent',
            name='event_view',
            field=models.ManyToManyField(blank=True, related_name='event_views', to='CPL.userip'),
        ),
    ]
