# Generated by Django 4.0.4 on 2022-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPL', '0002_rename_user_id_eventparticipatinggroup_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipatinggroup',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='eventparticipatinggroup',
            name='member',
        ),
        migrations.AddField(
            model_name='eventparticipatinggroup',
            name='member',
            field=models.ManyToManyField(to='CPL.user'),
        ),
    ]
